### PR TITLE
Upgraded 4 gems plus ruby versions in .travis.yml file

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded 4 gems.
 * Upgraded ruby versions in .travis.yml file.

Feel free to comment on this PR if you have questions or suggestions.

### CODE REVIEW

**Comment by jasnow** [comment]
Monitoring checks for this new PR - 2 down - 1 to go.

**Comment by djberg96** [comment]
@jasnow Looks good. Any chance you could squash those commits?

**Comment by jasnow** [comment]
Unclear about Codacy status so closing PR.

**Comment by djberg96** [comment]
@jasnow I guess I missed it, what was Codacy complaining about?

**Comment by jasnow** [comment]
Codacy appeared to be in a infinite loop.

**Pull request closed without merging**
