### PR TITLE
Upgraded 5 gems and .travis.yml file

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded 5 gems and .travis.yml file.
 * Updated .travis.yml's ruby versions, allowable failures, no need for 'sudo: false".

I understand if you want to cherrypick.

### CODE REVIEW

**Comment by jasnow** [comment]
@djberg96 - Here is the PR I emailed you about.

**Comment by jasnow** [comment]
Glad I could help - Cheers.

**Comment by djberg96** [comment]
@jasnow Thanks!

**Comment by jasnow** [comment]
You are welcome.

**Pull request merged**
